use_frameworks!

platform :ios, '8.0'

target 'MLCategory_Example' do
  pod 'MLCategory', :path => '../'

  target 'MLCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
